/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ArtifactRead } from './artifact-read';
import { Links } from './links';

/**
 * 
 * @export
 * @interface ArtifactReadList
 */
export interface ArtifactReadList {

    /**
     * 
     * @type {string}
     * @memberof ArtifactReadList
     */
    id: ArtifactReadListIdEnum;

    /**
     * 
     * @type {string}
     * @memberof ArtifactReadList
     */
    type: ArtifactReadListTypeEnum;

    /**
     * 
     * @type {string}
     * @memberof ArtifactReadList
     */
    href: string;

    /**
     * 
     * @type {Array<ArtifactRead>}
     * @memberof ArtifactReadList
     */
    items?: Array<ArtifactRead>;

    /**
     * The offset specified in the request (if none was specified, the default offset is 0) (not implemented yet). 
     * @type {number}
     * @memberof ArtifactReadList
     */
    offset: number;

    /**
     * The limit specified in the request (if none was specified, use the endpoint\'s default pagination limit) (not implemented yet, always return number of items). 
     * @type {number}
     * @memberof ArtifactReadList
     */
    limit: number;

    /**
     * 
     * @type {Links}
     * @memberof ArtifactReadList
     */
    _links: Links;
}


/**
    * @export
    * @enum {string}
    */
export enum ArtifactReadListIdEnum {
    Artifacts = 'artifacts'
}

/**
    * @export
    * @enum {string}
    */
export enum ArtifactReadListTypeEnum {
    Collection = 'collection'
}








