/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Artifact } from './artifact';
import { ArtifactMetadata } from './artifact-metadata';

/**
 * 
 * @export
 * @interface ArtifactRead
 */
export interface ArtifactRead {

    /**
     * The digest of the artifact
     * @type {string}
     * @memberof ArtifactRead
     */
    id: string;

    /**
     * 
     * @type {string}
     * @memberof ArtifactRead
     */
    type: ArtifactReadTypeEnum;

    /**
     * 
     * @type {string}
     * @memberof ArtifactRead
     */
    href: string;

    /**
     * 
     * @type {ArtifactMetadata}
     * @memberof ArtifactRead
     */
    metadata: ArtifactMetadata;

    /**
     * 
     * @type {Artifact}
     * @memberof ArtifactRead
     */
    properties: Artifact;
}



/**
    * @export
    * @enum {string}
    */
export enum ArtifactReadTypeEnum {
    Artifact = 'artifact'
}






