/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * URLs to navigate the different pages. As of now we always only return a single page. 
 * @export
 * @interface Links
 */
export interface Links {

    /**
     * URL (with offset and limit parameters) of the previous page; only present if offset is greater than 0. 
     * @type {string}
     * @memberof Links
     */
    prev?: string;

    /**
     * URL (with offset and limit parameters) of the current page. 
     * @type {string}
     * @memberof Links
     */
    self?: string;

    /**
     * URL (with offset and limit parameters) of the next page; only present if offset + limit is less than the total number of elements. 
     * @type {string}
     * @memberof Links
     */
    next?: string;
}


