/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Metadata of the resource.
 * @export
 * @interface Metadata
 */
export interface Metadata {

    /**
     * The ISO 8601 creation timestamp.
     * @type {string}
     * @memberof Metadata
     */
    createdDate?: string;

    /**
     * Unique name of the identity that created the resource.
     * @type {string}
     * @memberof Metadata
     */
    createdBy?: string;

    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    createdByUserId?: string;

    /**
     * The ISO 8601 modified timestamp.
     * @type {string}
     * @memberof Metadata
     */
    lastModifiedDate?: string;

    /**
     * Unique name of the identity that last modified the resource.
     * @type {string}
     * @memberof Metadata
     */
    lastModifiedBy?: string;

    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    lastModifiedByUserId?: string;

    /**
     * Unique name of the resource.
     * @type {string}
     * @memberof Metadata
     */
    resourceURN?: string;
}


