/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RegistryFeatures } from './registry-features';
import { StorageUsage } from './storage-usage';
import { WeeklySchedule } from './weekly-schedule';

/**
 * 
 * @export
 * @interface RegistryProperties
 */
export interface RegistryProperties {

    /**
     * 
     * @type {WeeklySchedule}
     * @memberof RegistryProperties
     */
    garbageCollectionSchedule?: WeeklySchedule | null;

    /**
     * 
     * @type {string}
     * @memberof RegistryProperties
     */
    hostname?: string;

    /**
     * 
     * @type {string}
     * @memberof RegistryProperties
     */
    location: string;

    /**
     * 
     * @type {string}
     * @memberof RegistryProperties
     */
    name: string;

    /**
     * 
     * @type {StorageUsage}
     * @memberof RegistryProperties
     */
    storageUsage?: StorageUsage | null;

    /**
     * 
     * @type {RegistryFeatures}
     * @memberof RegistryProperties
     */
    features?: RegistryFeatures;
}


