/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Repository } from './repository';
import { RepositoryMetadata } from './repository-metadata';

/**
 * 
 * @export
 * @interface RepositoryRead
 */
export interface RepositoryRead {

    /**
     * 
     * @type {string}
     * @memberof RepositoryRead
     */
    id: string;

    /**
     * 
     * @type {string}
     * @memberof RepositoryRead
     */
    type: RepositoryReadTypeEnum;

    /**
     * 
     * @type {string}
     * @memberof RepositoryRead
     */
    href: string;

    /**
     * 
     * @type {RepositoryMetadata}
     * @memberof RepositoryRead
     */
    metadata: RepositoryMetadata;

    /**
     * 
     * @type {Repository}
     * @memberof RepositoryRead
     */
    properties: Repository;
}



/**
    * @export
    * @enum {string}
    */
export enum RepositoryReadTypeEnum {
    Repository = 'repository'
}






