/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PaginationLinks } from './pagination-links';
import { TokenResponse } from './token-response';

/**
 * 
 * @export
 * @interface TokensResponse
 */
export interface TokensResponse {

    /**
     * 
     * @type {PaginationLinks}
     * @memberof TokensResponse
     */
    _links: PaginationLinks;

    /**
     * 
     * @type {number}
     * @memberof TokensResponse
     */
    count: number;

    /**
     * 
     * @type {string}
     * @memberof TokensResponse
     */
    href?: string;

    /**
     * 
     * @type {string}
     * @memberof TokensResponse
     */
    id?: string;

    /**
     * 
     * @type {Array<TokenResponse>}
     * @memberof TokensResponse
     */
    items?: Array<TokenResponse> | null;

    /**
     * 
     * @type {number}
     * @memberof TokensResponse
     */
    limit: number;

    /**
     * 
     * @type {number}
     * @memberof TokensResponse
     */
    offset: number;

    /**
     * 
     * @type {number}
     * @memberof TokensResponse
     */
    total: number;

    /**
     * 
     * @type {string}
     * @memberof TokensResponse
     */
    type?: string;
}


