/* tslint:disable */
/* eslint-disable */
/**
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Credentials } from './credentials';
import { Scope } from './scope';

/**
 * 
 * @export
 * @interface TokenProperties
 */
export interface TokenProperties {

    /**
     * 
     * @type {Credentials}
     * @memberof TokenProperties
     */
    credentials: Credentials | null;

    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    expiryDate?: string | null;

    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    name: string;

    /**
     * 
     * @type {Array<Scope>}
     * @memberof TokenProperties
     */
    scopes?: Array<Scope> | null;

    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    status?: TokenPropertiesStatusEnum;
}






/**
    * @export
    * @enum {string}
    */
export enum TokenPropertiesStatusEnum {
    Enabled = 'enabled',
    Disabled = 'disabled'
}



